var guests = ["Alishba", "Faizan", "Adan"];
console.log("I'd like to invite", guests[0], "to dinner.");
console.log("I'd like to invite", guests[1], "to dinner.");
console.log("I'd like to invite", guests[2], "to dinner.");
console.log("Unfortunately", guests[2], "can't make it so I'm inviting Hammad to dinner.");
var guests2 = [];
console.log("Now I'm inviting", guests2[1], "to dinner.");
console.log("I'm inviting", guests2[3], "to dinner.");
console.log("I'm inviting", guests2[4], "to dinner.");
console.log("I've found a bigger dinner table so I'd like to invite three more people to join us.");
console.log("I'm also inviting", guests2[0], "to dinner.");
console.log("I'm also inviting", guests2[2], "to dinner.");
console.log("I'm also inviting", guests2[5], "to dinner");
console.log("Unfortunately our new dinner table cannot arrive in time for dinner so I can only invite two guests.");
console.log("I'm sorry", guests2[0], "I can't invite you to dinner.");
console.log("I'm sorry", guests2[2], "I can't invite you to dinner.");
console.log("I'm sorry", guests2[4], "I can't invite you to dinner.");
console.log("I'm sorry", guests2[5], "I can't invite you to dinner.");
console.log(guests2[1], "you're still invited to dinner.");
console.log(guests2[3], "you're still invited to dinner.");
